In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
np.random.seed(42)
n = 10000

df = pd.DataFrame({
    "Age": np.random.randint(17,26, n),
    "Gender": np.random.choice(["Male","Female"], n),
    "Attendance": np.random.randint(40, 101, n),
    "CGPA": np.round(np.random.uniform(4.5, 10, n),2),
    "Backlogs":np.random.randint(0,8,n),
    "FamilyIncome": np.random.randint(150000, 12000000, n),
    "StudyHours": np.round(np.random.uniform(0.5,8,n),1),
    "Scholarship": np.random.choice([0,1],n, p=[0.7,0.3]),
    "InternetAccess": np.random.choice([0,1],n, p=[0.15,0.85]),
    "Hostel": np.random.choice([0,1],n),
    "MentalStress": np.random.randint(1,11,n),
    "PartTimeJob": np.random.choice([0,1],n, p=[0.75,0.25])
})

In [3]:
df

,Age,Gender,Attendance,CGPA,Backlogs,FamilyIncome,StudyHours,Scholarship,InternetAccess,Hostel,MentalStress,PartTimeJob
0,23,Female,70,5.71,3,2744921,2.5,0,1,1,2,0
1,20,Female,45,6.17,6,8791810,1.2,0,1,0,1,1
2,24,Male,53,5.21,7,2874959,7.9,0,1,0,10,0
3,21,Female,97,5.87,0,10029209,6.2,0,0,1,5,0
4,23,Male,62,9.02,2,646632,0.5,0,1,0,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17,Female,70,4.77,6,2549318,7.5,1,1,1,4,0
9996,23,Male,48,7.05,5,7781440,5.5,0,1,0,5,0
9997,22,Male,61,9.10,0,7274217,2.8,1,1,0,4,0
9998,25,Female,50,5.49,5,9772777,5.2,1,1,1,6,1
9999,23,Female,56,5.30,5,10765720,5.0,1,1,0,3,0

In [4]:
# Low attendance | Low CGPA | Many Backlogs | High Stress
risk = (
    (df["Attendance"] < 65).astype(int) +
    (df["CGPA"]<6.0).astype(int) +
    (df["Backlogs"]>= 3).astype(int) +
    (df["MentalStress"]>=8).astype(int) +
    (df["StudyHours"]< 2).astype(int)   
)

df["Dropout"] = np.where(risk>= 3,1,0)

In [5]:
#df["Dropout"]

In [6]:
df.head()

,Age,Gender,Attendance,CGPA,Backlogs,FamilyIncome,StudyHours,Scholarship,InternetAccess,Hostel,MentalStress,PartTimeJob,Dropout
0,23,Female,70,5.71,3,2744921,2.5,0,1,1,2,0,0
1,20,Female,45,6.17,6,8791810,1.2,0,1,0,1,1,1
2,24,Male,53,5.21,7,2874959,7.9,0,1,0,10,0,1
3,21,Female,97,5.87,0,10029209,6.2,0,0,1,5,0,0
4,23,Male,62,9.02,2,646632,0.5,0,1,0,8,0,1

In [7]:
X = df.drop("Dropout",axis=1)
y = df["Dropout"]
X

,Age,Gender,Attendance,CGPA,Backlogs,FamilyIncome,StudyHours,Scholarship,InternetAccess,Hostel,MentalStress,PartTimeJob
0,23,Female,70,5.71,3,2744921,2.5,0,1,1,2,0
1,20,Female,45,6.17,6,8791810,1.2,0,1,0,1,1
2,24,Male,53,5.21,7,2874959,7.9,0,1,0,10,0
3,21,Female,97,5.87,0,10029209,6.2,0,0,1,5,0
4,23,Male,62,9.02,2,646632,0.5,0,1,0,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17,Female,70,4.77,6,2549318,7.5,1,1,1,4,0
9996,23,Male,48,7.05,5,7781440,5.5,0,1,0,5,0
9997,22,Male,61,9.10,0,7274217,2.8,1,1,0,4,0
9998,25,Female,50,5.49,5,9772777,5.2,1,1,1,6,1
9999,23,Female,56,5.30,5,10765720,5.0,1,1,0,3,0

In [8]:
# y
X = pd.get_dummies(X, drop_first=True)

In [9]:
X

,Age,Attendance,CGPA,Backlogs,FamilyIncome,StudyHours,Scholarship,InternetAccess,Hostel,MentalStress,PartTimeJob,Gender_Male
0,23,70,5.71,3,2744921,2.5,0,1,1,2,0,False
1,20,45,6.17,6,8791810,1.2,0,1,0,1,1,False
2,24,53,5.21,7,2874959,7.9,0,1,0,10,0,True
3,21,97,5.87,0,10029209,6.2,0,0,1,5,0,False
4,23,62,9.02,2,646632,0.5,0,1,0,8,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17,70,4.77,6,2549318,7.5,1,1,1,4,0,False
9996,23,48,7.05,5,7781440,5.5,0,1,0,5,0,True
9997,22,61,9.10,0,7274217,2.8,1,1,0,4,0,True
9998,25,50,5.49,5,9772777,5.2,1,1,1,6,1,False
9999,23,56,5.30,5,10765720,5.0,1,1,0,3,0,False

In [10]:
X_train, X_test, y_train, y_test =  train_test_split(
    X, 
    y, 
    test_size = 0.2,
    random_state = 41,
    stratify=y
)

In [11]:
X_train.shape

(8000, 12)

In [12]:
X_test.shape

(2000, 12)

In [13]:
y_train.shape

(8000,)

In [14]:
y_test.shape

(2000,)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB

In [16]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN":KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(),
    "XGBoost": XGBClassifier(),
    "Naive Bayes": GaussianNB()  
}

In [38]:
result = []
for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

In [60]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results = []

for name, model in models.items():

    # Train
    model.fit(X_train, y_train)

    # Predict class labels
    y_pred = model.predict(X_test)

    # Predict probabilities
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        # SVM without probability=True
        y_prob = y_pred

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred),
        "ROC AUC": roc_auc_score(y_test, y_prob)
    })

/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [68]:
result_df = pd.DataFrame(results)
result_df = result_df.sort_values(
    by="Accuracy",
    ascending = False
)
result_df

                 Model  Accuracy  Precision    Recall  F1 Score   ROC AUC
5              XGBoost    1.0000   1.000000  1.000000  1.000000  1.000000
2        Decision Tree    0.9995   1.000000  0.997908  0.998953  0.998954
3        Random Forest    0.9990   1.000000  0.995816  0.997904  1.000000
0  Logistic Regression    0.8605   0.769648  0.594142  0.670602  0.906339
4                  SVM    0.7610   0.000000  0.000000  0.000000  0.500000
6          Naive Bayes    0.7610   0.000000  0.000000  0.000000  0.647090
1                  KNN    0.7015   0.203980  0.085774  0.120766  0.486826